services:
    postgres:
        image: postgres:17
        container_name: postgres_container
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: mypassword123
            POSTGRES_DB: mydatabase
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: